const NotFoundException = require('../exceptions/NotFoundException');

module.exports = () => NotFoundException.throw();
